version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "click"
      - dependency-name: "colorama"
    registries:
      - pip_registry

registries:
  pip_registry:
    type: "python-index"
    url: "https://pypi.org/simple"
    token: "${{secrets.DEPENDABOT_TOKEN}}"