apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web-app-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-service
  template:
    metadata:
      labels:
        app: web-app-service
    spec:
      containers:
      - name: web-app-service-demo-container
        image: 022997318112.dkr.ecr.us-east-1.amazonaws.com/atc-web-app:latest