name: Deploy to production

on:
  push:
    branches:
      - develop

jobs:

  deploy:
    name: Build image
    runs-on: self-hosted
    environment: develop

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Create .env file for storing Dockerfile secrets
      env:
        python_environment: ${{ secrets.python_environment }}
      run: |
        touch .env
        echo python_environment="$python_environment" >> .env
        cat .env
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr-repo-python-app
        IMAGE_TAG: ${{ github.sha }}

      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest --secret id=my_env,src=.env .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY